= Asciidoc/asciidoctor experiments
Nuno Carvalho <https://github.com/ntfc>
// document type
:doctype: book
:toc:
:toclevels: 3
:source-highlighter: pygments
//:pygments-style: tango
:icons: font
:sectnums:
// do not show Chapter. on chapter labels
:chapter-label:
:attribute-missing: drop
ifdef::backend-pdf[]
:pdf-stylesdir: resources/themes/
:pdf-fontsdir: resources/fonts/
:pdf-style: evil
endif::backend-pdf[]

== TODO

Things that should work:

* evil theme should pick up some default settings
* Tables
** Borders
** Multicolumn/multirow
* Headers and footers
** Company logo on footer/header
** Borders
* Page margins
* Copyright notices
* Remove Chapter. from the chapter title
* Warning, tips, etc
* Font
* Table of contents

== Introduction

Lead is the lead paragraph. Output:

[.lead]
This is the lead paragraph.

NOTE: while asciidoctor-pdf is quite good, it cannot be used in corporate
documents because it lacks title_page customization, copyright notices, etc
which are fundamental.

These are the results of my experiments with `asciidoc` for project documentation.

TIP: See https://github.com/asciidoctor/asciidoctor-pdf/issues/337[#337] for
instructions on how to extend asciidoctor-pdf with ruby

[IMPORTANT]
====
To generate corporate documents with custom title_page, copyright notices, etc
we will need to write custom extensions to asciidoctor-pdf, while the theming
capabilities are not advanced.

To run a custom extension: 

[source,bash]
----
./asciidoctor-pdf/bin/asciidoctor-pdf -a pdf-stylesdir=resources/themes/ -a pdf-fontsdir=resources/fonts -a pdf-style=evil -r ./pdf-extensions.rb README.adoc # <1>
----
<1> Note that `-r` expects an executable, hence we have to pass the file with a
preceding `./`
====

// table with the relative width of the 3 columns specified in cols
[cols="1,1,2",options="header"]
|===
|Revision Date |Sections Revised |Description of Revisions 

|2015-07-21
|First Release
|All new content.

|2015-10-16
|Template.
|Changes to the document template.

.2+|2015-11-11
|Fixed issues
|Added list of issues fixed by this Patch. Added list of issues fixed by this Patch. Added list of issues fixed by this Patch. Added list of issues fixed by this Patch.

|Diffenrete Fixed issues
|ist of issues fixed by this Patch. Added list of issues fixed by this Patch. Added list of issues fixed by this Patch.
|===

The `---` will be a thematic break.

'''

And `<<<` will be a page break:

<<<

=== Examples

Sample code:

[source,java]
.Factorial.java
----
public class Factorial {

	public static void main(String[] args) {
		final int NUM_FACTS = 100;
		for(int i = 0; i < NUM_FACTS; i++)
			System.out.println( i + "! is " + factorial(i));
	}
	
	public static int factorial(int n) {
		int result = 1;
		for(int i = 2; i <= n; i++)
			result *= i;
		return result;
	}
}
----

==== A heading

Recommended practices.footnote:[http://asciidoctor.org/docs/asciidoc-recommended-practices/]

== Convert to HTML

[[convert-html]]
[source,bash]
----
asciidoctor README.adoc
----

== Convert to PDF

[[convert-pdf]]
[source,bash]
----
./asciidoctor-pdf/bin/asciidoctor-pdf README.adoc
----

== Convert to PDF with themes

[[convert-pdf-themes]]
[source,bash]
----
./asciidoctor-pdf/bin/asciidoctor-pdf -a pdf-stylesdir=resources/themes/ -a pdf-fontsdir=resources/fonts -a pdf-style=evil README.adoc
----

See:

. https://github.com/asciidoctor/asciidoctor-maven-examples/tree/master/asciidoctor-pdf-example
. https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc

This is just gibberish:

include::loremipsum.adoc[]

include::contact.adoc[leveloffset=+1]
